name: jala_workspace
publish_to: none

environment:
  sdk: ^3.11.0

workspace:
  - packages/jala_core
  - packages/jala_dio
  - packages/jala_http
  - packages/jala_graphql
  - packages/jala_websocket
  - packages/jala_ui
  - packages/jala
  - packages/jala/example
  - examples/jala_example
