name: jala_example
description: Jala network inspector example / manual QA rig.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.11.0
  flutter: ">=3.35.0"

resolution: workspace

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  http: ^1.2.0
  jala: ^0.2.0
  jala_dio: ^0.2.0
  jala_http: ^0.2.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
